spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/entrepatas
    username: entrepatas
    password: entrepatas_dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true